{
 "title": "Prod Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=~\".+-prod\"})>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(container) (increase(kube_pod_container_status_restarts_total{namespace=~\".+-prod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=~\".+-prod\"}>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container) (increase(kube_pod_container_status_restarts_total{namespace=~\".+-prod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(pod) (sum by(pod) (container_cpu_usage_seconds_total{namespace=~\".+-prod\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory by Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (sum by(pod) (container_memory_working_set_bytes{namespace=~\".+-prod\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}